# Site settings
name: Apsis Labs
title: Development Chop Shop
email: contact@apsis.io

description: >
  The Apsis Labs team offers a broad range of software development
  and design services. With experience in everything from web-based
  enterprise solutions to 3D games development, we provide years of
  practical experience in full-stack development of all sorts.

permalink: /blog/:year/:month/:day/:title
paginate_path: "/blog/:num/"
paginate: 5
gems: [jekyll-paginate, jekyll-assets, jekyll-tidy]

markdown: redcarpet
redcarpet:
  extensions: [footnotes, superscript, highlight, autolink]

# Assets settings
assets:
  css_compressor: sass
  cachebust: soft
  prefix: /assets
  features:
    automatic_img_size: false

exclude: [Gemfile, Gemfile.lock, Rakefile, README.md]
