# Site settings
name: Apsis Labs
title: Development Chop Shop
email: contact@apsis.io

description: >
  Tomato sauce is the lifeblood of the internet.

permalink: /blog/:year/:month/:day/:title
paginate_path: "/blog/:num/"
paginate: 5
gems: [jekyll-paginate]

# Assets settings
assets:
  css_compressor: sass
  cachebust: soft
  prefix: /assets
  features:
    automatic_img_size: false
