# Site settings
name: Apsis Labs
title: Development Chop Shop
email: contact@apsis.io

description: >
  Tomato sauce is the lifeblood of the internet.

url: "http://apsis.io"

# Assets settings
assets:
  css_compressor: sass
  cachebust: soft
  prefix: assets
